#!/bin/sh

{ [ -f "/opt/etc/config/dropbear.conf" ] && \
. /opt/etc/config/dropbear.conf; } || \
PORT=22

ENABLED=yes
PROCS="dropbear"
PROG="/opt/sbin/$PROCS"
ARGS="-p $PORT"
DESC="Dropbear server"

PID_FILE="/opt/var/run/$PROCS.pid"

SKIP_KILL=1
SKIP_RELOAD=1

. /opt/etc/init.d/rc.func
